language: csharp
solution: Simple_YouTube_Music_Player.sln
mono: none
dotnet: 2.1
before_install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ./Simple YouTube Music Player/Simple YouTube Music Player.csproj